name: Generate Snake Animation

# Controls when the workflow will run
on:
  # Runs at the end of every day
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run on every push to the master branch
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v5
      
      # Generates the snake  
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # GitHub username where the contribution graph will be fetched
          github_user_name: ${{ github.repository_owner }}
          # List of files to generate with dark theme as default
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?palette=github-dark&color_snake=green
      
      # Push the content of <build_dir> to a branch
      - name: Push snake animation to branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}