name: Update CP Stats

on:
  schedule:
    - cron: '0 12 * * 0' # Every Sunday at 12 PM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-cp-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update competitive programming stats
        run: python scripts/update_cp_stats.py

      - name: Commit & push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): update competitive programming stats"
            git push
          else
            echo "No changes to commit."
          fi